### ISSUE TITLE
IndexError for last batch of last epoch

### ISSUE THREAD

**Issue by thvasilo** [jakezhaojb/ARAE#4]
I got this error while training a full model yesterday:

```
Traceback (most recent call last):
  File "train.py", line 526, in <module>
    train_gan_d(train_data[random.randint(0, niter)])
IndexError: list index out of range
```
This happened for the last batch of the last epoch.

The relevant code block:

```Python
# train gan ----------------------------------
        for k in range(niter_gan):

            # train discriminator/critic
            for i in range(args.niters_gan_d):
                # feed a seen sample within this epoch; good for early training
                errD, errD_real, errD_fake = \
                    train_gan_d(train_data[random.randint(0, niter)])
```

It is possible that `train_data` can be populated with less elements than `niter` in the `batchify`function?

The argument list I had was pretty minimal: `python train.py --data_path /path/to/billion-word-data --cuda --no_earlystopping`

**Comment by jakezhaojb** [comment]
i experimented with just random indices -- it worked just fine. Let me push a commit on this real quick

**Comment by jakezhaojb** [comment]
@thvasilo I pushed the update. Please let me know if you have any further question!
